![Logo_unad](https://upload.wikimedia.org/wikipedia/commons/5/5f/Logo_unad.png)

<font size=3 color="midnightblue" face="arial">
<h1 align="center">Escuela de Ciencias Básicas, Tecnología e Ingeniería</h1>
</font>

<font size=3 color="navy" face="arial">
<h1 align="center">ECBTI</h1>
</font>

<font size=2 color="darkorange" face="arial">
<h1 align="center">Curso:</h1>
</font>

<font size=2 color="navy" face="arial">
<h1 align="center">Introducción al lenguaje de programación Python</h1>
</font>

<font size=1 color="darkorange" face="arial">
<h1 align="center">Febrero de 2020</h1>
</font>

<h2 align="center">Sesión 10a - Ecosistema Python - Numpy</h2>

## Instructor:
> <strong> *Carlos Alberto Álvarez Henao, I.C. Ph.D.* </strong> 

In [2]:
lista1 = [1,2,3]
lista2 = [4,5,6]
lista3 = lista1 + lista2
print(lista3)

[1, 2, 3, 4, 5, 6]


In [3]:
lista4 = []
for i in range(3):
    lista4.append(lista1[i]+lista2[i])
lista4

[5, 7, 9]

## Arrays de `NumPy`

### ¿Qué es `NumPy`?

- Una biblioteca para `Python`: `ndarray` + `ufunc`

- Los arrays multidimensionales (`ndarray`) nos permiten almacenar datos de manera estructurada

- Las funciones universales (`ufunc`) nos permiten operar con esos datos de manera eficiente

`Python` está organizado en módulos, que son archivos con extensión `*.py` que contienen funciones, variables y otros objetos, y paquetes, que son conjuntos de módulos. 


Cuando queremos utilizar objetos que están definidos en un módulo tenemos que *importarlo*, y una vez que lo hemos hecho podemos usar el operador "`.`" para ir descendiendo en la jerarquía de paquetes y acceder al objeto que necesitamos.

In [8]:
import numpy as np

In [ ]:
np.

In [6]:
import math

In [ ]:
math.

In [ ]:
np.random.

In [7]:
from numpy import random

In [ ]:
np.random.

Y de esta manera accedemos a la función `norm`, que calcula la norma (o módulo) de un array:

In [ ]:
np.linalg.

La función *norm* está dentro del paquete *linalg*, que a su vez está dentro del paquete NumPy.

In [ ]:
import numpy as np

In [ ]:
from numpy import *

In [ ]:
np.randint()

Para encontrar ayuda sobre cierto tema podemos usar la función `lookfor`:

In [11]:
np.lookfor("random")

Search results for 'random'
---------------------------
numpy.matlib.rand
    Return a matrix of random values with given shape.
numpy.matlib.randn
    Return a random matrix with data from the "standard normal" distribution.
numpy.flip
    Reverse the order of elements in an array along the given axis.
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.prod
    Return the product of array elements over a given axis.
numpy.empty
    Return a new array of given shape and type, without initializing entries.
numpy.stack
    Join a sequence of arrays along a new axis.
numpy.fliplr
    Flip array in the left/right direction.
numpy.flipud
    Flip array in the up/down direction.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.convolve
    Returns the discrete, linear convolution of two one-dimensional sequences.
numpy.histogram
    Compute the histogram of a set of data.
numpy.empty_like
    Return a new array with the same

### Constantes y funciones matemáticas

Además de arrays, NumPy contiene también constantes y funciones matemáticas de uso cotidiano.

In [12]:
pi

NameError: name 'pi' is not defined

In [13]:
np.e

2.718281828459045

In [14]:
np.pi

3.141592653589793

In [15]:
np.log(2)

0.6931471805599453

In [16]:
lista = np.log([-10., np.e, np.e**2, 0])
print(lista)

[ nan   1.   2. -inf]


In [18]:
type(list(lista))

list

In [19]:
milista=[1,2,3]
print(type(milista))

<class 'list'>


In [20]:
lista=[1,2,3,4]
print(lista)
type(lista)

[1, 2, 3, 4]


list

### ¿Qué es exactamente un array?

Un array de `NumPy` es una colección de `N` elementos, igual que una secuencia de `Python` (por ejemplo, una lista). 


- Tiene las mismas propiedades que una secuencia y alguna más. 


- Para crear un array, la forma más directa es pasarle una secuencia a la función `np.array`.

In [21]:
import numpy as np

In [22]:
lista1 = [1.,2.,3.]
lista2 = [4.,5.,6]
lista3 = lista1+lista2
print(lista3)
print(type(lista3))

[1.0, 2.0, 3.0, 4.0, 5.0, 6]
<class 'list'>


In [23]:
lista3 = []
for i in range(len(lista2)):
    lista3.append(lista1[i]+lista2[i])
print(lista3)

[5.0, 7.0, 9.0]


In [30]:
arreglo1 = np.array(["1","2","3"])
arreglo2 = np.array(["4","5","6"])
arreglo3 = arreglo1 + arreglo2
arreglo3
arreglo3.dtype

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U1') dtype('<U1') dtype('<U1')

Los arrays de `NumPy` son *homogéneos*, es decir, todos sus elementos son del mismo tipo. 


- Si le pasamos a `np.array` una secuencia con objetos de tipos diferentes, promocionará todos al tipo con más información. 


- Para acceder al tipo del `array`, podemos usar el atributo `dtype`.

In [31]:
a = np.array([1, 2., 3])
print(a)
print(a.dtype)

[1. 2. 3.]
float64


In [32]:
np.array([1, 2, "3"])

array(['1', '2', '3'], dtype='<U21')

<div class="alert alert-warning"> **Nota**: Si *NumPy* no entiende el tipo de datos o construimos un array con argumentos incorrectos devolverá un array con *dtype* *object*. Estos arrays rara vez son útiles y su aparición suele ser signo de que algo falla en nuestro programa.</div>

`NumPy` intentará automáticamente construir un `array` con el tipo adecuado teniendo en cuenta los datos de entrada, aunque nosotros podemos forzarlo.

In [40]:
a = np.array([1.,2.,3.],dtype=int)
print(a.dtype)
print(a)

int64
[1 2 3]


In [ ]:
np.array([1, 2, 3], dtype=complex)

También podemos convertir un array de un tipo a otro utilizando el método `.astype`.

In [41]:
a

array([1, 2, 3])

In [42]:
a.astype(float)

array([1., 2., 3.])

### Motivo: eficiencia

* Los CICLOS son costosos
* Eliminar bucles: **vectorizar** operaciones
* Los bucles se ejecutan en `Python`, las operaciones vectorizadas en `C`
* Las operaciones entre arrays de `NumPy` se realizan **elemento a elemento**

Ejemplo:

$$ a_{ij} = b_{ij} + c_{ij} $$

In [44]:
k = 10000
N, M = k, k
a = np.empty(k*k).reshape(N, M)
b = np.random.rand(k*k).reshape(N, M)
c = np.random.rand(k*k).reshape(N, M)

In [45]:
import time

In [46]:
#%%timeit

tin = time.time()
for i in range(N):
    for j in range(M):
        a[i, j] = b[i, j] + c[i, j]
tout = time.time()
elapsedt = tout - tin
print("el tiempo de solucion fue de: ", elapsedt)

el tiempo de solucion fue de:  71.1084349155426


In [47]:
#%%timeit
tin = time.time()
a = b + c
tout = time.time()
elapsedt = tout - tin
print("el tiempo de solucion fue de: ", elapsedt)

el tiempo de solucion fue de:  0.43818235397338867


¡1000 veces más rápido! Se hace fundamental **vectorizar** las operaciones y aprovechar al máximo la velocidad de `NumPy`.

### Indexación de arrays

Una de las herramientas más importantes a la hora de trabajar con arrays es el indexado. 


- Consiste en seleccionar elementos aislados o secciones de un array. 


- En este curso se verá la indexación básica, pero existen técnicas de indexación avanzada que convierten los arrays en herramientas potentísimas.

In [51]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12,13]])
print(a)

[list([1, 2, 3]) list([4, 5, 6]) list([7, 8, 9]) list([10, 11, 12, 13])]


In [52]:
a = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14],[15,16,17,18,19]])
print(a)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [53]:
for i in range(5):
    print(a[i,i])

1
5
9
13
19


In [54]:
print(a[2:4,3:5])

[[10 11]
 [13 14]]


Los índices se indican entre corchetes justo después del array. 


- Recuerda que en `Python` la indexación empieza en `0`. 

- Si recuperamos el primer elemento de un array de dos dimensiones, obtenemos la primera fila.

In [55]:
a[2][1]

8

En vez de usar `a[0][0]` para recuperar el primer elemento de la primera fila, podemos abreviar aún más la sintaxis:

In [56]:
print(a)
a[2, 1]

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [10 11 12 13 14]
 [15 16 17 18 19]]


8

No solo podemos recuperar un elemento aislado, sino también porciones del array, utilizando la sintaxis `[<inicio>:<final>:<salto>]`.

In [ ]:
print(a)
a[1:3, 1:3]

In [ ]:
a[:, 0:1]

### Creación de arrays

Muchos métodos y muy variados

- A partir de datos existentes: `array`, `copy`


- Unos y ceros: `empty`, `eye`, `ones`, `zeros`, `*_like`


- Rangos: `arange`, `linspace`, `logspace`, `meshgrid`


- Aleatorios: `rand`, `randn`

In [58]:
x = np.linspace(0,1,11)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [61]:
b = np.logspace(0,10,11)
print(b)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10]


### Unos y ceros

- `empty(shape)` crea un array con «basura», equivalente a no inicializarlo, ligeramente más rápido que `zeros` o `ones`


- `eye(N, M=None, k=0)` crea un array con unos en una diagonal y ceros en el resto


- `identity(n)` devuelve la matriz identidad


- Las funciones `*_like(a)` construyen arrays con el mismo tamaño que uno dado

In [63]:
np.identity(5).astype(float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
_.shape

Si la función recibe como argumento `shape`, debemos pasarle el número de filas y columnas como una tupla (es decir, encerrado entre paréntesis).

In [ ]:
np.identity(10)

<div class="alert alert-warning">**Nota**: Un error muy típico es tratar de construir un array llamando a la función con dos argumentos, como se ejemplifica en la celda siguiente. Esto produce un error, porque NumPy espera un solo argumento: una tupla con el número de filas y el número de columnas. Es conveniente asegurarse de cuál es el convenio en cada caso porque no siempre hay consistencia interna.</div>

In [64]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
n = 10
a = np.ones((n,n))

for i in range(1,n-1):
    for j in range(1,n-1):
        a[i,-j] = 0
        if i==j:
            a[i,j] = 2
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 2. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 2. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 2. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
i3 = np.identity(3)
i3

In [ ]:
i3.shape

In [ ]:
np.ones(i3.shape)

Si en lugar de pasar directamente la forma del array ya sabemos que queremos crear un array con la misma forma que otro, podemos usar las funciones `*_like`, que reciben un array en vez de una tupla.

In [ ]:
np.ones_like(i3)

### Rangos

- `linspace(start, stop, num=50)` devuelve números equiespaciados dentro de un intervalo


- `logspace(start, stop, num=50, base=10.0)` devuelve números equiespaciados según una escala logarítmica


- `meshgrid(x1, x2, ...)` devuelve matrices de n-coordenadas

In [ ]:
np.linspace(0, 1, num=11)

In [ ]:
np.logspace(0, 3)

La función `np.meshgrid` se utiliza mucho a la hora de representar funciones en dos dimensiones, y crea dos arrays: uno varía por filas y otro por columnas. Combinándolos, podemos evaluar la función en un cuadrado.

In [ ]:
x = np.linspace(0, 1, num=5)
y = np.linspace(0, 1, num=5)

xx, yy = np.meshgrid(x, y)

In [ ]:
xx, yy

In [ ]:
xx + 1j * yy

### Operaciones con arrays

Las **funciones universales** (`ufunc`) operan sobre arrays de NumPy elemento a elemento y siguiendo las reglas de _broadcasting_.

- Funciones matemáticas: `sin`, `cos`, `sqrt`, `exp`, ...


- Operaciones lógicas: `<`, `~`, ...


- Funciones lógicas: `all`, `any`, `isnan`, `allclose`, ...

**Nota**: Las funciones matemáticas siempre devuelven el mismo tipo de datos de entrada

In [ ]:
a = np.arange(2 * 3).reshape(2, 3)
a

In [ ]:
np.sqrt(a)

In [ ]:
np.sqrt(np.arange(-3, 3))

In [ ]:
np.arange(-3, 3).astype(complex)

In [ ]:
np.sqrt(_)

### Funciones de comparación

Las comparaciones devuelven un array de booleanos:

In [ ]:
1 == 1

In [ ]:
a = np.arange(6)
b = np.ones(6).astype(int)
a, b

In [ ]:
a < b

In [ ]:
np.any(a < b)

In [ ]:
np.all(a < b)

In [ ]:
a = np.arange(6).astype(float)
b = np.ones(6)
a, b

Las funciones `isclose` y `allclose` realizan comparaciones entre arrays especificando una tolerancia:

In [ ]:
a = 1.0000010003
b = 1.0000012345

In [ ]:
np.isclose(a, b, rtol=1e-7)

In [ ]:
np.allclose(a, b, rtol=1e-6)

**¡Importante!** Ni en Python ni en ningún otro lenguaje debemos hacer comparaciones exactas entre números de punto flotante. Las operaciones matemáticas con estos números producen casi siempre resultados poco intuitivos y hay que tener cuidado con ellas. Para una introducción a estas peculiaridades existe la [web](http://puntoflotante.org/)

In [ ]:
0.1 + 0.2 + 0.3

In [ ]:
0.3 + 0.2 + 0.1

In [ ]:
0.1 + 0.2 + 0.3 == 0.3 + 0.2 + 0.1

## Ejercicios

### Ejercicio 1.

1. Crear un array `z1` 3x4 lleno de ceros de tipo entero.
2. Crear un array `z2` 3x4 lleno de ceros salvo la primera fila que serán todo unos.
3. Crear un array `z3` 3x4 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

In [ ]:
a = np.zeros((3, 4))
a

In [ ]:
a[0, :] = 1
a

In [ ]:
b = np.zeros((3, 4))
b[-1] = np.arange(5, 9)
b

### Ejercicio 2.

1. Crea un vector de 10 elementos, siendo los impares unos y los pares doses.
2. Crea un «tablero de ajedrez», con unos en las casillas negras y ceros en las blancas.

In [ ]:
v = np.ones(10)
v

In [ ]:
v[::2] = 2
v

In [ ]:
tablero = np.zeros((8, 8))
tablero

In [ ]:
tablero[1::2, ::2] = 1
tablero[::2, 1::2] = 1
tablero

### Ejercicio 3.

1. Crea una matriz aleatoria 5x5 y halla los valores mínimo y máximo.
2. Normaliza esa matriz entre 0 y 1.

## Bibliografía

* Documentación de NumPy http://docs.scipy.org/doc/numpy
* Travis Oliphant, "Guide to NumPy" http://csc.ucdavis.edu/~chaos/courses/nlp/Software/NumPyBook.pdf
* SciPy Lecture Notes http://scipy-lectures.github.io
* Nicolas Rougier, "100 NumPy exercises" http://www.loria.fr/~rougier/teaching/numpy.100/index.html